---
name: Create release

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calendar Version
        uses: harm-matthias-harms/calendar-version@v1
        id: calendar-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: v

      - name: Update jsr.json version
        uses: restackio/update-json-file-action@2.1
        with:
          file: package.json
          fields: '{"version": "${{ steps.calendar-version.outputs.new-version }}"}'

      - name: Update package.json version
        uses: restackio/update-json-file-action@2.1
        with:
          file: package.json
          fields: '{"version": "${{ steps.calendar-version.outputs.new-version }}"}'

      - name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: jsr.json package.json
          default_author: github_actions
          fetch: false
          message: Version bump
          tag: ${{ steps.calendar-version.outputs.new-tag }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.2.1
        with:
          draft: false
          generate_release_notes: true
          make_latest: true
          prerelease: false
          tag_name: ${{ steps.calendar-version.outputs.new-tag }}
